import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { stringify } from "smol-toml";
import type { Profile } from "../types";
import { loadProfiles } from "./profiles";
import { upsertManagedBlock } from "./ssh-config";
import {
  backupsDir, globalGitConfigPath, managedGitConfigPath, profilesPath,
  sshiftConfigDir, sshConfigPath, type PathContext,
} from "../utils/paths";
import { runCommand, type CommandRunner } from "../utils/shell";

const GIT_START = "# --- sshift git start ---";
const GIT_END = "# --- sshift git end ---";

export function identityConfigPath(profile: Profile, ctx?: PathContext): string {
  const id = createHash("sha256").update(profile.name).digest("hex");
  return join(sshiftConfigDir(ctx), "identities", `${id}.conf`);
}

export function quoteGit(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"').replaceAll("\n", "\\n").replaceAll("\t", "\\t")}"`;
}

export function remotePatterns(profile: Profile): string[] {
  return [
    `*@${profile.host}:*`, `*@${profile.host}:*/**`,
    `${profile.host}:*`, `${profile.host}:*/**`,
    `ssh://*@${profile.host}/**`, `ssh://*@${profile.host}:*/**`,
    `ssh://${profile.host}/**`, `ssh://${profile.host}:*/**`,
    `https://${profile.host}/**`, `https://*@${profile.host}/**`,
    `https://${profile.host}:*/**`,
    `https://*@${profile.host}:*/**`,
  ];
}

export function renderGitRouting(profiles: Profile[], ctx?: PathContext): string {
  const lines = ["# Generated by sshift. Use sshift add --edit to change identities."];
  for (const profile of profiles) {
    if (!profile.git_name || !profile.git_email) continue;
    for (const pattern of remotePatterns(profile)) {
      lines.push(`[includeIf ${quoteGit(`hasconfig:remote.*.url:${pattern}`)}]`);
      lines.push(`  path = ${quoteGit(identityConfigPath(profile, ctx))}`);
    }
  }
  return `${lines.join("\n")}\n`;
}

export function upsertGitInclude(existing: string, includePath?: string): string {
  const start = existing.indexOf(GIT_START);
  const end = existing.indexOf(GIT_END);
  if ((start === -1) !== (end === -1) || (start !== -1 && end < start)) {
    throw new Error("The sshift Git config block is incomplete. Restore it from a backup before continuing.");
  }
  const base = start === -1 ? existing : existing.slice(0, start) + existing.slice(end + GIT_END.length).replace(/^\r?\n/, "");
  if (!includePath) return base;
  return `${base}${base && !base.endsWith("\n") ? "\n" : ""}${GIT_START}\n[include]\n  path = ${quoteGit(includePath)}\n${GIT_END}\n`;
}

export async function requireIdentityGit(runner: CommandRunner = runCommand): Promise<void> {
  const result = await runner("git", ["--version"]);
  const match = result.stdout.match(/git version (\d+)\.(\d+)/);
  if (result.exitCode !== 0 || !match || Number(match[1]) < 2 || (Number(match[1]) === 2 && Number(match[2]) < 36)) {
    throw new Error("Automatic Git author selection requires Git 2.36 or newer. Please update Git first.");
  }
}

export function validateProfiles(profiles: Profile[]): void {
  const names = new Set<string>();
  const hosts = new Set<string>();
  for (const profile of profiles) {
    if (!profile.name.trim() || /[\r\n]/.test(profile.name)) throw new Error("Identity name must be a non-empty single line.");
    if (names.has(profile.name)) throw new Error(`Identity already exists: ${profile.name}`);
    if (hosts.has(profile.host)) throw new Error(`Host already has an identity: ${profile.host}. Use an SSH alias for another account.`);
    for (const host of [profile.host, profile.hostname]) {
      if (!/^[a-z\d][a-z\d.-]*$/i.test(host)) throw new Error(`Invalid SSH host: ${host}`);
    }
    if (!/^[a-z\d_][a-z\d_.-]*$/i.test(profile.user)) throw new Error(`Invalid SSH user: ${profile.user}`);
    for (const value of [profile.identity_file, profile.git_name, profile.git_email]) {
      if (value !== undefined && (!value.trim() || /[\r\n\0]/.test(value))) throw new Error("Key paths and Git author values must be non-empty single lines.");
    }
    names.add(profile.name);
    hosts.add(profile.host);
  }
}

export async function readOptionalFile(path: string): Promise<string | undefined> {
  try {
    if (!(await stat(path)).isFile()) throw new Error(`Configuration path is not a regular file: ${path}`);
    return await readFile(path, "utf8");
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") return undefined;
    throw error;
  }
}

// All owned files and the include entry are restored if any write fails.
export async function saveAndApplyProfiles(
  profiles: Profile[],
  reason: string,
  ctx?: PathContext,
  write: (path: string, content: string) => Promise<void> = async (path, content) => {
    await mkdir(dirname(path), { recursive: true, mode: 0o700 });
    await writeFile(path, content, { encoding: "utf8", mode: 0o600 });
  },
): Promise<string> {
  validateProfiles(profiles);
  const previous = await loadProfiles(ctx);
  const sshPath = sshConfigPath(ctx);
  const gitPath = globalGitConfigPath(ctx);
  const routingPath = managedGitConfigPath(ctx);
  const updates = new Map<string, string | undefined>();
  updates.set(sshPath, upsertManagedBlock((await readOptionalFile(sshPath)) ?? "", profiles));
  updates.set(routingPath, profiles.length ? renderGitRouting(profiles, ctx) : undefined);
  updates.set(gitPath, upsertGitInclude((await readOptionalFile(gitPath)) ?? "", profiles.length ? routingPath : undefined));
  for (const profile of previous.profiles) updates.set(identityConfigPath(profile, ctx), undefined);
  for (const profile of profiles) {
    if (profile.git_name && profile.git_email) {
      updates.set(identityConfigPath(profile, ctx), `[user]\n  name = ${quoteGit(profile.git_name)}\n  email = ${quoteGit(profile.git_email)}\n`);
    }
  }
  updates.set(profilesPath(ctx), stringify({ profiles }));
  const snapshots = await Promise.all([...updates.keys()].map(async (path) => ({ path, content: await readOptionalFile(path) })));
  const backup = join(backupsDir(ctx), `identity-${Date.now()}-${randomUUID()}.json`);
  await mkdir(dirname(backup), { recursive: true, mode: 0o700 });
  await writeFile(backup, JSON.stringify({ reason, files: snapshots }, null, 2), { mode: 0o600 });
  const changed: string[] = [];
  try {
    for (const [path, content] of updates) {
      changed.push(path);
      if (content === undefined) await rm(path, { force: true });
      else await write(path, content);
    }
  } catch (error) {
    const failures: string[] = [];
    for (const snapshot of snapshots.filter((file) => changed.includes(file.path)).reverse()) {
      try {
        if (snapshot.content === undefined) await rm(snapshot.path, { force: true });
        else await writeFile(snapshot.path, snapshot.content, "utf8");
      } catch { failures.push(snapshot.path); }
    }
    if (failures.length) throw new Error(`Could not restore ${failures.join(", ")}. Backup: ${backup}`, { cause: error });
    throw error;
  }
  return backup;
}
